name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: pdf/PartWhole-Preprint.pdf
