name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site content
        run: |
          set -e
          rm -rf site
          mkdir -p site/presentation

          cp -R presentation/* site/presentation/

          npm init -y >/dev/null 2>&1
          npm i reveal.js@5 sass

          mkdir -p site/presentation/dist site/presentation/plugin
          cp -R node_modules/reveal.js/dist/* site/presentation/dist/
          cp -R node_modules/reveal.js/plugin/* site/presentation/plugin/

          mkdir -p site/presentation/dist/theme
          npx sass \
            --style=expanded --no-source-map \
            --load-path node_modules/reveal.js/css/theme \
            --load-path node_modules/reveal.js/css/theme/source \
            --load-path site/presentation/css/theme/source \
            site/presentation/css/theme/source/custom.scss:site/presentation/dist/theme/custom.css

          cp pdf/PartWhole-Preprint.pdf site/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
