name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-bibtex-extra \
          texlive-science \
          latexmk

      - name: Compile LaTeX document
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error 25-VisShort-PartWhole-Preprint.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: anchoringAndAlignmentDataFactors.pdf
